/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int r(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int r_alloc_mem(void);
int r_init_mem(int mem);
void r_free_mem(int mem);
int r_checkout(void);
void r_release(int mem);
void r_incref(void);
void r_decref(void);
casadi_int r_n_in(void);
casadi_int r_n_out(void);
casadi_real r_default_in(casadi_int i);
const char* r_name_in(casadi_int i);
const char* r_name_out(casadi_int i);
const casadi_int* r_sparsity_in(casadi_int i);
const casadi_int* r_sparsity_out(casadi_int i);
int r_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int r_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define r_SZ_ARG 6
#define r_SZ_RES 2
#define r_SZ_IW 0
#define r_SZ_W 0
int dr_dy(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dr_dy_alloc_mem(void);
int dr_dy_init_mem(int mem);
void dr_dy_free_mem(int mem);
int dr_dy_checkout(void);
void dr_dy_release(int mem);
void dr_dy_incref(void);
void dr_dy_decref(void);
casadi_int dr_dy_n_in(void);
casadi_int dr_dy_n_out(void);
casadi_real dr_dy_default_in(casadi_int i);
const char* dr_dy_name_in(casadi_int i);
const char* dr_dy_name_out(casadi_int i);
const casadi_int* dr_dy_sparsity_in(casadi_int i);
const casadi_int* dr_dy_sparsity_out(casadi_int i);
int dr_dy_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dr_dy_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dr_dy_SZ_ARG 6
#define dr_dy_SZ_RES 1
#define dr_dy_SZ_IW 0
#define dr_dy_SZ_W 0
int h(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int h_alloc_mem(void);
int h_init_mem(int mem);
void h_free_mem(int mem);
int h_checkout(void);
void h_release(int mem);
void h_incref(void);
void h_decref(void);
casadi_int h_n_in(void);
casadi_int h_n_out(void);
casadi_real h_default_in(casadi_int i);
const char* h_name_in(casadi_int i);
const char* h_name_out(casadi_int i);
const casadi_int* h_sparsity_in(casadi_int i);
const casadi_int* h_sparsity_out(casadi_int i);
int h_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int h_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define h_SZ_ARG 4
#define h_SZ_RES 1
#define h_SZ_IW 0
#define h_SZ_W 0
int collision_h(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int collision_h_alloc_mem(void);
int collision_h_init_mem(int mem);
void collision_h_free_mem(int mem);
int collision_h_checkout(void);
void collision_h_release(int mem);
void collision_h_incref(void);
void collision_h_decref(void);
casadi_int collision_h_n_in(void);
casadi_int collision_h_n_out(void);
casadi_real collision_h_default_in(casadi_int i);
const char* collision_h_name_in(casadi_int i);
const char* collision_h_name_out(casadi_int i);
const casadi_int* collision_h_sparsity_in(casadi_int i);
const casadi_int* collision_h_sparsity_out(casadi_int i);
int collision_h_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int collision_h_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define collision_h_SZ_ARG 4
#define collision_h_SZ_RES 1
#define collision_h_SZ_IW 0
#define collision_h_SZ_W 0
int rollout(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int rollout_alloc_mem(void);
int rollout_init_mem(int mem);
void rollout_free_mem(int mem);
int rollout_checkout(void);
void rollout_release(int mem);
void rollout_incref(void);
void rollout_decref(void);
casadi_int rollout_n_in(void);
casadi_int rollout_n_out(void);
casadi_real rollout_default_in(casadi_int i);
const char* rollout_name_in(casadi_int i);
const char* rollout_name_out(casadi_int i);
const casadi_int* rollout_sparsity_in(casadi_int i);
const casadi_int* rollout_sparsity_out(casadi_int i);
int rollout_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int rollout_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define rollout_SZ_ARG 4
#define rollout_SZ_RES 1
#define rollout_SZ_IW 0
#define rollout_SZ_W 0
int get_n(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int get_n_alloc_mem(void);
int get_n_init_mem(int mem);
void get_n_free_mem(int mem);
int get_n_checkout(void);
void get_n_release(int mem);
void get_n_incref(void);
void get_n_decref(void);
casadi_int get_n_n_in(void);
casadi_int get_n_n_out(void);
casadi_real get_n_default_in(casadi_int i);
const char* get_n_name_in(casadi_int i);
const char* get_n_name_out(casadi_int i);
const casadi_int* get_n_sparsity_in(casadi_int i);
const casadi_int* get_n_sparsity_out(casadi_int i);
int get_n_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int get_n_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define get_n_SZ_ARG 0
#define get_n_SZ_RES 1
#define get_n_SZ_IW 0
#define get_n_SZ_W 0
int get_m(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int get_m_alloc_mem(void);
int get_m_init_mem(int mem);
void get_m_free_mem(int mem);
int get_m_checkout(void);
void get_m_release(int mem);
void get_m_incref(void);
void get_m_decref(void);
casadi_int get_m_n_in(void);
casadi_int get_m_n_out(void);
casadi_real get_m_default_in(casadi_int i);
const char* get_m_name_in(casadi_int i);
const char* get_m_name_out(casadi_int i);
const casadi_int* get_m_sparsity_in(casadi_int i);
const casadi_int* get_m_sparsity_out(casadi_int i);
int get_m_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int get_m_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define get_m_SZ_ARG 0
#define get_m_SZ_RES 1
#define get_m_SZ_IW 0
#define get_m_SZ_W 0
int K_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int K_0_alloc_mem(void);
int K_0_init_mem(int mem);
void K_0_free_mem(int mem);
int K_0_checkout(void);
void K_0_release(int mem);
void K_0_incref(void);
void K_0_decref(void);
casadi_int K_0_n_in(void);
casadi_int K_0_n_out(void);
casadi_real K_0_default_in(casadi_int i);
const char* K_0_name_in(casadi_int i);
const char* K_0_name_out(casadi_int i);
const casadi_int* K_0_sparsity_in(casadi_int i);
const casadi_int* K_0_sparsity_out(casadi_int i);
int K_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int K_0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define K_0_SZ_ARG 6
#define K_0_SZ_RES 1
#define K_0_SZ_IW 0
#define K_0_SZ_W 0
int K_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int K_1_alloc_mem(void);
int K_1_init_mem(int mem);
void K_1_free_mem(int mem);
int K_1_checkout(void);
void K_1_release(int mem);
void K_1_incref(void);
void K_1_decref(void);
casadi_int K_1_n_in(void);
casadi_int K_1_n_out(void);
casadi_real K_1_default_in(casadi_int i);
const char* K_1_name_in(casadi_int i);
const char* K_1_name_out(casadi_int i);
const casadi_int* K_1_sparsity_in(casadi_int i);
const casadi_int* K_1_sparsity_out(casadi_int i);
int K_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int K_1_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define K_1_SZ_ARG 6
#define K_1_SZ_RES 1
#define K_1_SZ_IW 0
#define K_1_SZ_W 0
int K_2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int K_2_alloc_mem(void);
int K_2_init_mem(int mem);
void K_2_free_mem(int mem);
int K_2_checkout(void);
void K_2_release(int mem);
void K_2_incref(void);
void K_2_decref(void);
casadi_int K_2_n_in(void);
casadi_int K_2_n_out(void);
casadi_real K_2_default_in(casadi_int i);
const char* K_2_name_in(casadi_int i);
const char* K_2_name_out(casadi_int i);
const casadi_int* K_2_sparsity_in(casadi_int i);
const casadi_int* K_2_sparsity_out(casadi_int i);
int K_2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int K_2_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define K_2_SZ_ARG 6
#define K_2_SZ_RES 1
#define K_2_SZ_IW 0
#define K_2_SZ_W 0
int K_3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int K_3_alloc_mem(void);
int K_3_init_mem(int mem);
void K_3_free_mem(int mem);
int K_3_checkout(void);
void K_3_release(int mem);
void K_3_incref(void);
void K_3_decref(void);
casadi_int K_3_n_in(void);
casadi_int K_3_n_out(void);
casadi_real K_3_default_in(casadi_int i);
const char* K_3_name_in(casadi_int i);
const char* K_3_name_out(casadi_int i);
const casadi_int* K_3_sparsity_in(casadi_int i);
const casadi_int* K_3_sparsity_out(casadi_int i);
int K_3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int K_3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define K_3_SZ_ARG 6
#define K_3_SZ_RES 1
#define K_3_SZ_IW 0
#define K_3_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
