/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int J_alloc_mem(void);
int J_init_mem(int mem);
void J_free_mem(int mem);
int J_checkout(void);
void J_release(int mem);
void J_incref(void);
void J_decref(void);
casadi_int J_n_in(void);
casadi_int J_n_out(void);
casadi_real J_default_in(casadi_int i);
const char* J_name_in(casadi_int i);
const char* J_name_out(casadi_int i);
const casadi_int* J_sparsity_in(casadi_int i);
const casadi_int* J_sparsity_out(casadi_int i);
int J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define J_SZ_ARG 5
#define J_SZ_RES 1
#define J_SZ_IW 0
#define J_SZ_W 0
int Jfi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Jfi_alloc_mem(void);
int Jfi_init_mem(int mem);
void Jfi_free_mem(int mem);
int Jfi_checkout(void);
void Jfi_release(int mem);
void Jfi_incref(void);
void Jfi_decref(void);
casadi_int Jfi_n_in(void);
casadi_int Jfi_n_out(void);
casadi_real Jfi_default_in(casadi_int i);
const char* Jfi_name_in(casadi_int i);
const char* Jfi_name_out(casadi_int i);
const casadi_int* Jfi_sparsity_in(casadi_int i);
const casadi_int* Jfi_sparsity_out(casadi_int i);
int Jfi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int Jfi_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Jfi_SZ_ARG 4
#define Jfi_SZ_RES 1
#define Jfi_SZ_IW 0
#define Jfi_SZ_W 0
int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int f_alloc_mem(void);
int f_init_mem(int mem);
void f_free_mem(int mem);
int f_checkout(void);
void f_release(int mem);
void f_incref(void);
void f_decref(void);
casadi_int f_n_in(void);
casadi_int f_n_out(void);
casadi_real f_default_in(casadi_int i);
const char* f_name_in(casadi_int i);
const char* f_name_out(casadi_int i);
const casadi_int* f_sparsity_in(casadi_int i);
const casadi_int* f_sparsity_out(casadi_int i);
int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define f_SZ_ARG 5
#define f_SZ_RES 1
#define f_SZ_IW 0
#define f_SZ_W 0
int h(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int h_alloc_mem(void);
int h_init_mem(int mem);
void h_free_mem(int mem);
int h_checkout(void);
void h_release(int mem);
void h_incref(void);
void h_decref(void);
casadi_int h_n_in(void);
casadi_int h_n_out(void);
casadi_real h_default_in(casadi_int i);
const char* h_name_in(casadi_int i);
const char* h_name_out(casadi_int i);
const casadi_int* h_sparsity_in(casadi_int i);
const casadi_int* h_sparsity_out(casadi_int i);
int h_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int h_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define h_SZ_ARG 4
#define h_SZ_RES 1
#define h_SZ_IW 0
#define h_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
