/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) car_merge_kinematic_bicycle_casadi_N3_T20_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {3, 4, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {63, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};

/* J:(i0[3x4],i1[2],i2[3],i3[4],i4[63])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[2]? arg[2][0] : 0;
  a00=(a00*a01);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[2]? arg[2][1] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[0]? arg[0][2] : 0;
  a04=arg[2]? arg[2][2] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[4]? arg[4][15] : 0;
  a02=(a02*a01);
  a05=arg[4]? arg[4][16] : 0;
  a05=(a05*a03);
  a02=(a02+a05);
  a05=arg[4]? arg[4][17] : 0;
  a05=(a05*a04);
  a02=(a02+a05);
  a02=(a00-a02);
  a05=arg[4]? arg[4][27] : 0;
  a05=(a02*a05);
  a06=arg[0]? arg[0][3] : 0;
  a06=(a06*a01);
  a07=arg[0]? arg[0][4] : 0;
  a07=(a07*a03);
  a06=(a06+a07);
  a07=arg[0]? arg[0][5] : 0;
  a07=(a07*a04);
  a06=(a06+a07);
  a07=arg[4]? arg[4][18] : 0;
  a07=(a07*a01);
  a08=arg[4]? arg[4][19] : 0;
  a08=(a08*a03);
  a07=(a07+a08);
  a08=arg[4]? arg[4][20] : 0;
  a08=(a08*a04);
  a07=(a07+a08);
  a07=(a06-a07);
  a08=arg[4]? arg[4][28] : 0;
  a08=(a07*a08);
  a05=(a05+a08);
  a08=arg[0]? arg[0][6] : 0;
  a08=(a08*a01);
  a09=arg[0]? arg[0][7] : 0;
  a09=(a09*a03);
  a08=(a08+a09);
  a09=arg[0]? arg[0][8] : 0;
  a09=(a09*a04);
  a08=(a08+a09);
  a09=arg[4]? arg[4][21] : 0;
  a09=(a09*a01);
  a10=arg[4]? arg[4][22] : 0;
  a10=(a10*a03);
  a09=(a09+a10);
  a10=arg[4]? arg[4][23] : 0;
  a10=(a10*a04);
  a09=(a09+a10);
  a09=(a08-a09);
  a10=arg[4]? arg[4][29] : 0;
  a10=(a09*a10);
  a05=(a05+a10);
  a10=arg[0]? arg[0][9] : 0;
  a10=(a10*a01);
  a11=arg[0]? arg[0][10] : 0;
  a11=(a11*a03);
  a10=(a10+a11);
  a11=arg[0]? arg[0][11] : 0;
  a11=(a11*a04);
  a10=(a10+a11);
  a11=arg[4]? arg[4][24] : 0;
  a11=(a11*a01);
  a01=arg[4]? arg[4][25] : 0;
  a01=(a01*a03);
  a11=(a11+a01);
  a01=arg[4]? arg[4][26] : 0;
  a01=(a01*a04);
  a11=(a11+a01);
  a11=(a10-a11);
  a01=arg[4]? arg[4][30] : 0;
  a01=(a11*a01);
  a05=(a05+a01);
  a05=(a05*a02);
  a01=arg[4]? arg[4][31] : 0;
  a01=(a02*a01);
  a04=arg[4]? arg[4][32] : 0;
  a04=(a07*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][33] : 0;
  a04=(a09*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][34] : 0;
  a04=(a11*a04);
  a01=(a01+a04);
  a01=(a01*a07);
  a05=(a05+a01);
  a01=arg[4]? arg[4][35] : 0;
  a01=(a02*a01);
  a04=arg[4]? arg[4][36] : 0;
  a04=(a07*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][37] : 0;
  a04=(a09*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][38] : 0;
  a04=(a11*a04);
  a01=(a01+a04);
  a01=(a01*a09);
  a05=(a05+a01);
  a01=arg[4]? arg[4][39] : 0;
  a02=(a02*a01);
  a01=arg[4]? arg[4][40] : 0;
  a07=(a07*a01);
  a02=(a02+a07);
  a07=arg[4]? arg[4][41] : 0;
  a09=(a09*a07);
  a02=(a02+a09);
  a09=arg[4]? arg[4][42] : 0;
  a09=(a11*a09);
  a02=(a02+a09);
  a02=(a02*a11);
  a05=(a05+a02);
  a02=arg[4]? arg[4][43] : 0;
  a02=(a00*a02);
  a11=arg[4]? arg[4][44] : 0;
  a11=(a06*a11);
  a02=(a02+a11);
  a11=arg[4]? arg[4][45] : 0;
  a11=(a08*a11);
  a02=(a02+a11);
  a11=arg[4]? arg[4][46] : 0;
  a11=(a10*a11);
  a02=(a02+a11);
  a02=(a02*a00);
  a11=arg[4]? arg[4][47] : 0;
  a11=(a00*a11);
  a09=arg[4]? arg[4][48] : 0;
  a09=(a06*a09);
  a11=(a11+a09);
  a09=arg[4]? arg[4][49] : 0;
  a09=(a08*a09);
  a11=(a11+a09);
  a09=arg[4]? arg[4][50] : 0;
  a09=(a10*a09);
  a11=(a11+a09);
  a11=(a11*a06);
  a02=(a02+a11);
  a11=arg[4]? arg[4][51] : 0;
  a11=(a00*a11);
  a09=arg[4]? arg[4][52] : 0;
  a09=(a06*a09);
  a11=(a11+a09);
  a09=arg[4]? arg[4][53] : 0;
  a09=(a08*a09);
  a11=(a11+a09);
  a09=arg[4]? arg[4][54] : 0;
  a09=(a10*a09);
  a11=(a11+a09);
  a11=(a11*a08);
  a02=(a02+a11);
  a11=arg[4]? arg[4][55] : 0;
  a00=(a00*a11);
  a11=arg[4]? arg[4][56] : 0;
  a06=(a06*a11);
  a00=(a00+a06);
  a06=arg[4]? arg[4][57] : 0;
  a08=(a08*a06);
  a00=(a00+a08);
  a08=arg[4]? arg[4][58] : 0;
  a08=(a10*a08);
  a00=(a00+a08);
  a00=(a00*a10);
  a02=(a02+a00);
  a05=(a05+a02);
  a02=arg[1]? arg[1][0] : 0;
  a00=arg[4]? arg[4][59] : 0;
  a00=(a02*a00);
  a10=arg[1]? arg[1][1] : 0;
  a08=arg[4]? arg[4][60] : 0;
  a08=(a10*a08);
  a00=(a00+a08);
  a00=(a00*a02);
  a08=arg[4]? arg[4][61] : 0;
  a02=(a02*a08);
  a08=arg[4]? arg[4][62] : 0;
  a08=(a10*a08);
  a02=(a02+a08);
  a02=(a02*a10);
  a00=(a00+a02);
  a05=(a05+a00);
  if (res[0]!=0) res[0][0]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* Jfi:(i0[3x4],i1[3],i2[4],i3[63])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  a00=arg[0]? arg[0][0] : 0;
  a01=arg[1]? arg[1][0] : 0;
  a00=(a00*a01);
  a02=arg[0]? arg[0][1] : 0;
  a03=arg[1]? arg[1][1] : 0;
  a02=(a02*a03);
  a00=(a00+a02);
  a02=arg[0]? arg[0][2] : 0;
  a04=arg[1]? arg[1][2] : 0;
  a02=(a02*a04);
  a00=(a00+a02);
  a02=arg[3]? arg[3][15] : 0;
  a02=(a02*a01);
  a05=arg[3]? arg[3][16] : 0;
  a05=(a05*a03);
  a02=(a02+a05);
  a05=arg[3]? arg[3][17] : 0;
  a05=(a05*a04);
  a02=(a02+a05);
  a02=(a00-a02);
  a05=arg[3]? arg[3][27] : 0;
  a05=(a02*a05);
  a06=arg[0]? arg[0][3] : 0;
  a06=(a06*a01);
  a07=arg[0]? arg[0][4] : 0;
  a07=(a07*a03);
  a06=(a06+a07);
  a07=arg[0]? arg[0][5] : 0;
  a07=(a07*a04);
  a06=(a06+a07);
  a07=arg[3]? arg[3][18] : 0;
  a07=(a07*a01);
  a08=arg[3]? arg[3][19] : 0;
  a08=(a08*a03);
  a07=(a07+a08);
  a08=arg[3]? arg[3][20] : 0;
  a08=(a08*a04);
  a07=(a07+a08);
  a07=(a06-a07);
  a08=arg[3]? arg[3][28] : 0;
  a08=(a07*a08);
  a05=(a05+a08);
  a08=arg[0]? arg[0][6] : 0;
  a08=(a08*a01);
  a09=arg[0]? arg[0][7] : 0;
  a09=(a09*a03);
  a08=(a08+a09);
  a09=arg[0]? arg[0][8] : 0;
  a09=(a09*a04);
  a08=(a08+a09);
  a09=arg[3]? arg[3][21] : 0;
  a09=(a09*a01);
  a10=arg[3]? arg[3][22] : 0;
  a10=(a10*a03);
  a09=(a09+a10);
  a10=arg[3]? arg[3][23] : 0;
  a10=(a10*a04);
  a09=(a09+a10);
  a09=(a08-a09);
  a10=arg[3]? arg[3][29] : 0;
  a10=(a09*a10);
  a05=(a05+a10);
  a10=arg[0]? arg[0][9] : 0;
  a10=(a10*a01);
  a11=arg[0]? arg[0][10] : 0;
  a11=(a11*a03);
  a10=(a10+a11);
  a11=arg[0]? arg[0][11] : 0;
  a11=(a11*a04);
  a10=(a10+a11);
  a11=arg[3]? arg[3][24] : 0;
  a11=(a11*a01);
  a01=arg[3]? arg[3][25] : 0;
  a01=(a01*a03);
  a11=(a11+a01);
  a01=arg[3]? arg[3][26] : 0;
  a01=(a01*a04);
  a11=(a11+a01);
  a11=(a10-a11);
  a01=arg[3]? arg[3][30] : 0;
  a01=(a11*a01);
  a05=(a05+a01);
  a05=(a05*a02);
  a01=arg[3]? arg[3][31] : 0;
  a01=(a02*a01);
  a04=arg[3]? arg[3][32] : 0;
  a04=(a07*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][33] : 0;
  a04=(a09*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][34] : 0;
  a04=(a11*a04);
  a01=(a01+a04);
  a01=(a01*a07);
  a05=(a05+a01);
  a01=arg[3]? arg[3][35] : 0;
  a01=(a02*a01);
  a04=arg[3]? arg[3][36] : 0;
  a04=(a07*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][37] : 0;
  a04=(a09*a04);
  a01=(a01+a04);
  a04=arg[3]? arg[3][38] : 0;
  a04=(a11*a04);
  a01=(a01+a04);
  a01=(a01*a09);
  a05=(a05+a01);
  a01=arg[3]? arg[3][39] : 0;
  a02=(a02*a01);
  a01=arg[3]? arg[3][40] : 0;
  a07=(a07*a01);
  a02=(a02+a07);
  a07=arg[3]? arg[3][41] : 0;
  a09=(a09*a07);
  a02=(a02+a09);
  a09=arg[3]? arg[3][42] : 0;
  a09=(a11*a09);
  a02=(a02+a09);
  a02=(a02*a11);
  a05=(a05+a02);
  a02=arg[3]? arg[3][43] : 0;
  a02=(a00*a02);
  a11=arg[3]? arg[3][44] : 0;
  a11=(a06*a11);
  a02=(a02+a11);
  a11=arg[3]? arg[3][45] : 0;
  a11=(a08*a11);
  a02=(a02+a11);
  a11=arg[3]? arg[3][46] : 0;
  a11=(a10*a11);
  a02=(a02+a11);
  a02=(a02*a00);
  a11=arg[3]? arg[3][47] : 0;
  a11=(a00*a11);
  a09=arg[3]? arg[3][48] : 0;
  a09=(a06*a09);
  a11=(a11+a09);
  a09=arg[3]? arg[3][49] : 0;
  a09=(a08*a09);
  a11=(a11+a09);
  a09=arg[3]? arg[3][50] : 0;
  a09=(a10*a09);
  a11=(a11+a09);
  a11=(a11*a06);
  a02=(a02+a11);
  a11=arg[3]? arg[3][51] : 0;
  a11=(a00*a11);
  a09=arg[3]? arg[3][52] : 0;
  a09=(a06*a09);
  a11=(a11+a09);
  a09=arg[3]? arg[3][53] : 0;
  a09=(a08*a09);
  a11=(a11+a09);
  a09=arg[3]? arg[3][54] : 0;
  a09=(a10*a09);
  a11=(a11+a09);
  a11=(a11*a08);
  a02=(a02+a11);
  a11=arg[3]? arg[3][55] : 0;
  a00=(a00*a11);
  a11=arg[3]? arg[3][56] : 0;
  a06=(a06*a11);
  a00=(a00+a06);
  a06=arg[3]? arg[3][57] : 0;
  a08=(a08*a06);
  a00=(a00+a08);
  a08=arg[3]? arg[3][58] : 0;
  a08=(a10*a08);
  a00=(a00+a08);
  a00=(a00*a10);
  a02=(a02+a00);
  a05=(a05+a02);
  if (res[0]!=0) res[0][0]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int Jfi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Jfi_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Jfi_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Jfi_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Jfi_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Jfi_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Jfi_incref(void) {
}

CASADI_SYMBOL_EXPORT void Jfi_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Jfi_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Jfi_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Jfi_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Jfi_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Jfi_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Jfi_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Jfi_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Jfi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Jfi_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* f:(i0[4],i1[2],i2[3],i3[4],i4[63])->(o0[4]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a3=tan(a3);
  a4=2.;
  a3=(a3/a4);
  a3=atan(a3);
  a4=(a2+a3);
  a4=cos(a4);
  a4=(a1*a4);
  a5=arg[4]? arg[4][0] : 0;
  a4=(a4*a5);
  a0=(a0+a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a4=(a2+a3);
  a4=sin(a4);
  a4=(a1*a4);
  a4=(a4*a5);
  a0=(a0+a4);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a0*a5);
  a0=(a1+a0);
  if (res[0]!=0) res[0][2]=a0;
  a3=sin(a3);
  a1=(a1*a3);
  a1=(a1*a5);
  a2=(a2+a1);
  if (res[0]!=0) res[0][3]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* h:(i0[4],i1[4],i2[4],i3[63])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[3]? arg[3][14] : 0;
  a0=casadi_sq(a0);
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a1=casadi_sq(a1);
  a2=arg[0]? arg[0][1] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a2=(a2-a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int h_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int h_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int h_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_release(int mem) {
}

CASADI_SYMBOL_EXPORT void h_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int h_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int h_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real h_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
