/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int r(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int r_alloc_mem(void);
int r_init_mem(int mem);
void r_free_mem(int mem);
int r_checkout(void);
void r_release(int mem);
void r_incref(void);
void r_decref(void);
casadi_int r_n_in(void);
casadi_int r_n_out(void);
casadi_real r_default_in(casadi_int i);
const char* r_name_in(casadi_int i);
const char* r_name_out(casadi_int i);
const casadi_int* r_sparsity_in(casadi_int i);
const casadi_int* r_sparsity_out(casadi_int i);
int r_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int r_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define r_SZ_ARG 6
#define r_SZ_RES 1
#define r_SZ_IW 0
#define r_SZ_W 0
int dr_dy(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dr_dy_alloc_mem(void);
int dr_dy_init_mem(int mem);
void dr_dy_free_mem(int mem);
int dr_dy_checkout(void);
void dr_dy_release(int mem);
void dr_dy_incref(void);
void dr_dy_decref(void);
casadi_int dr_dy_n_in(void);
casadi_int dr_dy_n_out(void);
casadi_real dr_dy_default_in(casadi_int i);
const char* dr_dy_name_in(casadi_int i);
const char* dr_dy_name_out(casadi_int i);
const casadi_int* dr_dy_sparsity_in(casadi_int i);
const casadi_int* dr_dy_sparsity_out(casadi_int i);
int dr_dy_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dr_dy_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dr_dy_SZ_ARG 6
#define dr_dy_SZ_RES 1
#define dr_dy_SZ_IW 0
#define dr_dy_SZ_W 0
int get_n(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int get_n_alloc_mem(void);
int get_n_init_mem(int mem);
void get_n_free_mem(int mem);
int get_n_checkout(void);
void get_n_release(int mem);
void get_n_incref(void);
void get_n_decref(void);
casadi_int get_n_n_in(void);
casadi_int get_n_n_out(void);
casadi_real get_n_default_in(casadi_int i);
const char* get_n_name_in(casadi_int i);
const char* get_n_name_out(casadi_int i);
const casadi_int* get_n_sparsity_in(casadi_int i);
const casadi_int* get_n_sparsity_out(casadi_int i);
int get_n_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int get_n_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define get_n_SZ_ARG 0
#define get_n_SZ_RES 1
#define get_n_SZ_IW 0
#define get_n_SZ_W 0
int get_m(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int get_m_alloc_mem(void);
int get_m_init_mem(int mem);
void get_m_free_mem(int mem);
int get_m_checkout(void);
void get_m_release(int mem);
void get_m_incref(void);
void get_m_decref(void);
casadi_int get_m_n_in(void);
casadi_int get_m_n_out(void);
casadi_real get_m_default_in(casadi_int i);
const char* get_m_name_in(casadi_int i);
const char* get_m_name_out(casadi_int i);
const casadi_int* get_m_sparsity_in(casadi_int i);
const casadi_int* get_m_sparsity_out(casadi_int i);
int get_m_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int get_m_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define get_m_SZ_ARG 0
#define get_m_SZ_RES 1
#define get_m_SZ_IW 0
#define get_m_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
