/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int r(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int r_alloc_mem(void);
int r_init_mem(int mem);
void r_free_mem(int mem);
int r_checkout(void);
void r_release(int mem);
void r_incref(void);
void r_decref(void);
casadi_int r_n_in(void);
casadi_int r_n_out(void);
casadi_real r_default_in(casadi_int i);
const char* r_name_in(casadi_int i);
const char* r_name_out(casadi_int i);
const casadi_int* r_sparsity_in(casadi_int i);
const casadi_int* r_sparsity_out(casadi_int i);
int r_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int r_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define r_SZ_ARG 1
#define r_SZ_RES 1
#define r_SZ_IW 0
#define r_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
